# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# based on example at https://github.com/hadley/tibble/blob/master/.travis.yml
# Explanation of .Rbuildignore and other things:  http://jtleek.com/protocols/travis_bioc_devel/
# Details for 'language: r' specification:  https://docs.travis-ci.com/user/languages/r/
# Online check for syntax of .travis.yml (but doesn't work for R format):  http://lint.travis-ci.org/

#language: c
#
#before_install:
#  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
#  - chmod 755 ./travis-tool.sh
#  - ./travis-tool.sh bootstrap
#install:
#  - ./travis-tool.sh install_deps
#script: ./travis-tool.sh run_tests
#
#after_failure:
#  - ./travis-tool.sh dump_logs
#
#notifications:
#  email:
#    on_success: change
#    on_failure: change
#

language: r
cache: packages

r_packages:
  - utils
  - stats
  - testthat
  - mapproj
  - maptools
  - deldir
  - PBSmapping
  - RANN
  - colorspace
  - RandomFields
  - shape
  - devtools
  - mixtools
  - sp
  - maps
  - mapdata
  - TMB

r_github_packages:
  - kaskr/TMB_contrib_R/TMBhelper
  - nwfsc-assess/geostatistical_delta-GLMM

warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change
